<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/DataCleaningPandas28Aug2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Cleaning Pandas Bro Code
https://youtu.be/Ck0QgwiCEIs?si=Uw3fLmJRITcJfA6Y

In [3]:
import pandas as pd
#pd.set_option('display.max.columns', None)
#pd.set_option('display.max.rows', None)
df=pd.read_csv('/content/world_population.csv')
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [7]:
#df=df.drop(columns=["CCA3"])
df.head(5)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [9]:
df=df.drop(columns=['1990 Population','1980 Population'])
df.head(5)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,19860.0,468.0,170.5641,1.0100,0.00

In [10]:
df=df.dropna(subset=['2022 Population'])
df.head(5)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,19860.0,468.0,170.5641,1.0100,0.00

In [12]:
print(df.to_string())

     Rank                           Country              Capital      Continent  2022 Population  2020 Population  2015 Population  2010 Population  2000 Population  1970 Population  Area (km²)  Density (per km²)  Growth Rate  World Population Percentage
0      36                       Afghanistan                Kabul           Asia     4.112877e+07     3.897223e+07     3.375350e+07     2.818967e+07     1.954298e+07       10752971.0    652230.0            63.0587       1.0257                         0.52
1     138                           Albania               Tirana         Europe     2.842321e+06     2.866849e+06     2.882481e+06     2.913399e+06     3.182021e+06        2324731.0     28748.0            98.8702       0.9957                         0.04
2      34                           Algeria              Algiers         Africa     4.490322e+07     4.345167e+07     3.954315e+07     3.585634e+07     3.077462e+07       13795915.0   2381741.0            18.8531       1.0164                         0.56
3     213                    American Samoa            Pago Pago        Oceania     4.427300e+04     4.618900e+04     5.136800e+04     5.484900e+04     5.823000e+04          27075.0       199.0           222.4774       0.9831                         0.00
4     203                           Andorra     Andorra la Vella         Europe     7.982400e+04     7.770000e+04     7.174600e+04     7.151900e+04     6.609700e+04          19860.0       468.0           170.5641       1.0100                         0.00
5      42                            Angola               Luanda         Africa     3.558899e+07     3.342848e+07     2.812772e+07     2.336418e+07     1.639406e+07        6029700.0   1246700.0            28.5466       1.0315                         0.45
6     224                          Anguilla           The Valley  North America     1.585700e+04     1.558500e+04     1.452500e+04     1.317200e+04     1.104700e+04           6283.0        91.0           174.2527       1.0066                         0.00
7     201               Antigua and Barbuda         Saint John’s  North America     9.376300e+04     9.266400e+04     8.994100e+04     8.569500e+04     7.505500e+04          64516.0       442.0           212.1335       1.0058                         0.00
8      33                         Argentina         Buenos Aires  South America     4.551032e+07     4.503603e+07     4.325706e+07     4.110012e+07     3.707077e+07       23842803.0   2780400.0            16.3683       1.0052                         0.57
9     140                           Armenia              Yerevan           Asia     2.780469e+06     2.805608e+06     2.878595e+06     2.946293e+06     3.168523e+06        2534377.0     29743.0            93.4831       0.9962                         0.03
10    198                             Aruba           Oranjestad  North America     1.064450e+05     1.065850e+05     1.042570e+05     1.003410e+05     8.910100e+04          59106.0       180.0           591.3611       0.9991                         0.00
11     55                         Australia             Canberra        Oceania     2.617741e+07     2.567005e+07     2.382024e+07     2.201917e+07     1.901796e+07       12595034.0   7692024.0             3.4032       1.0099                         0.33
12     99                           Austria               Vienna         Europe     8.939617e+06     8.907777e+06     8.642421e+06     8.362829e+06     8.010428e+06        7465301.0     83871.0           106.5877       1.0020                         0.11
13     91                        Azerbaijan                 Baku           Asia     1.035807e+07              NaN     9.863480e+06     9.237202e+06     8.190337e+06        5425317.0     86600.0           119.6082       1.0044                         0.13
14    176                           Bahamas               Nassau  North America     4.099840e+05     4.064710e+05     3.926970e+05     3.732720e+05     3.250140e+05         179129.0     13943.0            29.4043       1.0051                         0.01
15    154                           Bahrain               Manama           Asia     1.472233e+06     1.477469e+06     1.362142e+06     1.213645e+06     7.114420e+05         222555.0       765.0          1924.4876       1.0061                         0.02
16      8                        Bangladesh                Dhaka           Asia     1.711864e+08     1.674210e+08     1.578300e+08     1.483911e+08     1.291933e+08       67541860.0    147570.0          1160.0350       1.0108                         2.15
17    186                          Barbados           Bridgetown  North America     2.816350e+05     2.806930e+05     2.780830e+05     2.747110e+05     2.646570e+05         241397.0       430.0           654.9651       1.0015                         0.00
18     96                           Belarus                Minsk         Europe     9.534954e+06     9.633740e+06     9.700609e+06     9.731427e+06     1.025648e+07        9170786.0    207600.0            45.9295       0.9955                         0.12
19     81                           Belgium             Brussels         Europe     1.165593e+07     1.156172e+07     1.124830e+07     1.087795e+07     1.026434e+07        9629376.0     30528.0           381.8111       1.0038                         0.15
20    177                            Belize             Belmopan  North America     4.052720e+05     3.949210e+05     3.598710e+05     3.221060e+05     2.404060e+05         120905.0     22966.0            17.6466       1.0131                         0.01
21     77                             Benin           Porto-Novo         Africa     1.335286e+07     1.264312e+07     1.093278e+07     9.445710e+06     6.998023e+06        3023443.0    112622.0           118.5635       1.0274                         0.17
22    206                           Bermuda             Hamilton  North America     6.418400e+04     6.403100e+04     6.314400e+04     6.344700e+04     6.137100e+04          52019.0        54.0          1188.5926       1.0000                         0.00
23    165                            Bhutan              Thimphu           Asia     7.824550e+05     7.725060e+05     7.432740e+05     7.055160e+05     5.872070e+05         298894.0     38394.0            20.3796       1.0064                         0.01
24     80                           Bolivia                Sucre  South America     1.222411e+07     1.193616e+07     1.109008e+07     1.022327e+07     8.592656e+06        4585693.0   1098581.0            11.1272       1.0120                         0.15
25    137            Bosnia and Herzegovina             Sarajevo         Europe     3.233526e+06     3.318407e+06     3.524324e+06     3.811088e+06     4.179350e+06        3815561.0     51209.0            63.1437       0.9886                         0.04
26    144                          Botswana             Gaborone         Africa     2.630296e+06     2.546402e+06     2.305171e+06     2.091664e+06     1.726985e+06         592244.0    582000.0             4.5194       1.0162                         0.03
27      7                            Brazil             Brasilia  South America     2.153135e+08     2.131963e+08     2.051882e+08     1.963535e+08     1.758737e+08       96369875.0   8515767.0            25.2841       1.0046                         2.70
28    221            British Virgin Islands            Road Town  North America     3.130500e+04     3.091000e+04     2.936600e+04     2.755600e+04     2.010400e+04           9581.0       151.0           207.3179       1.0059                         0.00
29    175                            Brunei  Bandar Seri Begawan           Asia     4.490020e+05     4.417250e+05     4.214370e+05     3.960530e+05     3.339260e+05         133343.0      5765.0            77.8841       1.0081                         0.01
30    108                          Bulgaria                Sofia         Europe     6.781953e+06     6.979175e+06     7.309253e+06     7.592273e+06     8.097691e+06        8582950.0    110879.0            61.1654       0.9849                         0.09
31     58                      Burkina Faso          Ouagadougou         Africa     2.267376e+07     2.152263e+07     1.871802e+07     1.611684e+07     1.188289e+07        5611666.0    272967.0            83.0641       1.0259                         0.28
32     78                           Burundi            Bujumbura         Africa     1.288958e+07     1.222023e+07     1.072715e+07     9.126605e+06     6.307659e+06        3497834.0     27834.0           463.0874       1.0270                         0.16
33     73                          Cambodia           Phnom Penh           Asia     1.676784e+07     1.639686e+07     1.541752e+07     1.436353e+07     1.211884e+07        6708525.0    181035.0            92.6221       1.0108                         0.21
34     53                          Cameroon              Yaounde         Africa     2.791454e+07     2.649109e+07     2.301265e+07     1.987804e+07     1.509159e+07        6452787.0    475442.0            58.7128       1.0263                         0.35
35     39                            Canada               Ottawa  North America     3.845433e+07     3.788870e+07     3.573213e+07     3.396341e+07     3.068331e+07       21434577.0   9984670.0             3.8513       1.0078                         0.48
36    171                        Cape Verde                Praia         Africa     5.931490e+05     5.826400e+05     5.521660e+05     5.212120e+05     4.582510e+05         287262.0      4033.0           147.0739       1.0089                         0.01
37    205                    Cayman Islands          George Town  North America     6.870600e+04     6.731100e+04     6.091100e+04     5.407400e+04     3.965800e+04          10533.0       264.0           260.2500       1.0084                         0.00
38    117          Central African Republic               Bangui         Africa     5.579144e+06     5.343020e+06     4.819333e+06     4.660067e+06     3.759170e+06        2067356.0    622984.0             8.9555       1.0224                         0.07
39     69                              Chad            N'Djamena         Africa     1.772332e+07     1.664470e+07     1.414027e+07     1.189473e+07     8.259137e+06        3667394.0   1284000.0            13.8032       1.0316                         0.22
40     65                             Chile             Santiago  South America     1.960373e+07     1.930032e+07     1.787012e+07     1.700416e+07     1.535180e+07        9820481.0    756102.0            25.9274       1.0057                         0.25
41      1                             China              Beijing           Asia     1.425887e+09     1.424930e+09     1.393715e+09     1.348191e+09     1.264099e+09      822534450.0   9706961.0           146.8933       1.0000                        17.88
42     28                          Colombia               Bogota  South America     5.187402e+07     5.093066e+07     4.711973e+07              NaN     3.921514e+07       20905254.0   1141748.0            45.4339       1.0069                         0.65
43    163                           Comoros               Moroni         Africa     8.367740e+05     8.061660e+05     7.302160e+05     6.560240e+05     5.367580e+05         242351.0      1862.0           449.3953       1.0184                         0.01
44    223                      Cook Islands               Avarua        Oceania     1.701100e+04     1.702900e+04     1.769500e+04     1.721200e+04     1.589700e+04          20470.0       236.0            72.0805       1.0005                         0.00
45    124                        Costa Rica             San José  North America     5.180829e+06     5.123105e+06     4.895242e+06     4.622252e+06     3.979193e+06        1855697.0     51100.0           101.3861       1.0052                         0.06
46    130                           Croatia               Zagreb         Europe     4.030358e+06     4.096868e+06     4.254815e+06     4.368682e+06     4.548434e+06        4492638.0     56594.0            71.2153       0.9927                         0.05
47     85                              Cuba               Havana  North America     1.121219e+07     1.130070e+07     1.133989e+07     1.129042e+07     1.110579e+07        8869636.0    109884.0           102.0366       0.9961                         0.14
48    189                           Curacao           Willemstad  North America     1.911630e+05     1.892880e+05     1.695720e+05     1.593800e+05     1.414240e+05         150385.0       444.0           430.5473       1.0043                         0.00
49    158                            Cyprus              Nicosia         Europe     1.251488e+06     1.237537e+06     1.187280e+06     1.129686e+06     9.482370e+05         640804.0      9251.0           135.2814       1.0059                         0.02
50     88                    Czech Republic               Prague         Europe     1.049399e+07     1.053095e+07     1.052380e+07     1.046475e+07     1.023471e+07        9795744.0     78865.0           133.0627       0.9984                         0.13
51    115                           Denmark           Copenhagen         Europe     5.882261e+06     5.825641e+06     5.677796e+06     5.550849e+06     5.340655e+06        4922963.0     43094.0           136.4984       1.0048                         0.07
52    160                          Djibouti             Djibouti         Africa     1.120849e+06     1.090156e+06     1.006259e+06     9.191990e+05     7.420330e+05         144379.0     23200.0            48.3125       1.0138                         0.01
53    204                          Dominica               Roseau  North America     7.273700e+04     7.199500e+04     7.000700e+04     6.875500e+04     6.834600e+04          68895.0       751.0            96.8535       1.0045                         0.00
54     84                Dominican Republic        Santo Domingo  North America     1.122882e+07     1.099966e+07     1.040583e+07     9.775755e+06     8.540791e+06        4475871.0     48671.0           230.7087       1.0100                         0.14
55     15                          DR Congo             Kinshasa         Africa     9.901021e+07     9.285316e+07     7.865690e+07     6.639126e+07     4.861632e+07       20151733.0   2344858.0            42.2244       1.0325                         1.24
56     67                           Ecuador                Quito  South America     1.800100e+07     1.758860e+07     1.619590e+07     1.498958e+07     1.262651e+07        6172215.0    276841.0            65.0229       1.0114                         0.23
57     14                             Egypt                Cairo         Africa     1.109901e+08     1.074651e+08     9.772380e+07     8.725241e+07     7.137137e+07       34781986.0   1002450.0           110.7188       1.0158                         1.39
58    112                       El Salvador         San Salvador  North America     6.336392e+06     6.292731e+06     6.231066e+06     6.114034e+06     5.958482e+06        3619090.0     21041.0           301.1450       1.0035                         0.08
59    152                 Equatorial Guinea               Malabo         Africa     1.674908e+06     1.596049e+06              NaN     1.094524e+06     6.849770e+05         316955.0     28051.0            59.7094       1.0247                         0.02
60    132                           Eritrea               Asmara         Africa     3.684032e+06     3.555868e+06     3.340006e+06     3.147727e+06     2.392880e+06        1272748.0    117600.0            31.3268       1.0176                         0.05
61    156                           Estonia              Tallinn         Europe     1.326062e+06     1.329444e+06     1.314657e+06     1.331535e+06     1.396877e+06        1361999.0     45227.0            29.3201       0.9980                         0.02
63     12                          Ethiopia          Addis Ababa         Africa     1.233799e+08     1.171909e+08     1.024719e+08     8.923779e+07     6.703187e+07       28308246.0   1104300.0           111.7268       1.0257                         1.55
64    231                  Falkland Islands              Stanley  South America     3.780000e+03     3.747000e+03     3.408000e+03     3.187000e+03     3.080000e+03           2274.0     12173.0             0.3105       1.0043                         0.00
65    209                     Faroe Islands             Tórshavn         Europe     5.309000e+04     5.241500e+04     4.881600e+04     4.841000e+04     4.566000e+04          38416.0      1393.0            38.1120       1.0038                         0.00
66    162                              Fiji                 Suva        Oceania     9.297660e+05     9.204220e+05     9.172000e+05     9.051690e+05     8.325090e+05         527634.0     18272.0            50.8847       1.0056                         0.01
67    118                           Finland             Helsinki         Europe     5.540745e+06     5.529468e+06     5.479461e+06     5.363271e+06     5.176209e+06        4606621.0    338424.0            16.3722       1.0009                         0.07
68     23                            France                Paris         Europe     6.462663e+07     6.448005e+07     6.380977e+07     6.244457e+07     5.866545e+07       50523586.0    551695.0           117.1419       1.0015                         0.81
69    184                     French Guiana              Cayenne  South America     3.045570e+05     2.909690e+05     2.570260e+05     2.284530e+05     1.643510e+05          46484.0     83534.0             3.6459       1.0239                         0.00
70    183                  French Polynesia              Papeete        Oceania     3.062790e+05     3.019200e+05     2.917870e+05     2.837880e+05     2.509270e+05         117891.0      4167.0            73.5011       1.0074                         0.00
71    146                             Gabon           Libreville         Africa     2.388992e+06     2.292573e+06     2.028517e+06     1.711105e+06     1.272935e+06         597192.0    267668.0             8.9252       1.0204                         0.03
72    142                            Gambia               Banjul         Africa     2.705992e+06     2.573995e+06     2.253133e+06              NaN              NaN              NaN     10689.0           253.1567       1.0250                         0.03
73    131                           Georgia              Tbilisi           Asia     3.744385e+06     3.765912e+06     3.771132e+06              NaN              NaN              NaN     69700.0            53.7214       0.9964                         0.05
74     19                           Germany               Berlin         Europe     8.336984e+07     8.332899e+07     8.207323e+07     8.132509e+07     8.155168e+07       78294583.0    357114.0           233.4544       0.9995                         1.05
75     47                             Ghana                Accra         Africa     3.347587e+07     3.218040e+07     2.887094e+07     2.557472e+07     1.966550e+07        8861895.0    238533.0           140.3406       1.0196                         0.42
76    219                         Gibraltar            Gibraltar         Europe     3.264900e+04     3.270900e+04     3.252000e+04     3.126200e+04     2.774100e+04          26685.0         6.0          5441.5000       0.9994                         0.00
77     90                            Greece               Athens         Europe     1.038497e+07     1.051223e+07     1.080664e+07     1.103378e+07     1.103811e+07        8544873.0    131990.0            78.6800       0.9942                         0.13

In [15]:
df=df.fillna({"Country": "None"})
df.head(5)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,19860.0,468.0,170.5641,1.0100,0.00

In [17]:
#df['Continent']=df['Continent'].replace(to_replace="Oceania", value="New Continent")
df['Capital']=df['Capital'].replace({"Kabul":"Afghan Capital","Tirana":"Albabia Capital"})
df.head(5)

,Rank,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,Afghanistan,Afghan Capital,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,Albania,Albabia Capital,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,American Samoa,Pago Pago,New Continent,44273.0,46189.0,51368.0,54849.0,58230.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,19860.0,468.0,170.5641,1.0100,0.00

In [4]:
df['Country']=df['Country'].str.lower()
df.head(5)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,american samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00

In [ ]:
#df['columnname']=df['columnname'].astype(bool)
df=df.drop_duplicates()