<a href="https://colab.research.google.com/github/kamalakk/Data-Analysis/blob/main/PandasDatetime_10Sep2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas Date time 10 Sep 2026

In [2]:
import pandas as pd
import datetime as dt

In [6]:
today = dt.date(2019,7,12)
#today.year
today.month
#today.day

7

In [14]:
datewithtimestamp = dt.datetime(2020,1,23,23,54,34)
print(datewithtimestamp)
datewithtimestamp.hour
datewithtimestamp.minute
datewithtimestamp.second
#datewithtimestamp.microsecond

2020-01-23 23:54:34

34

In [21]:
#pd.Timestamp("2022-2-15")
#pd.Timestamp("2022/2/15")
#pd.Timestamp("2022, 2, 15")
pd.Timestamp("2022-2-15 15:12:13")
# pd.Timestamp("2022-2-15 15:12:13 PM")

Timestamp('2022-02-15 15:12:13')

In [24]:
from numpy import dtype
dates = ["2022-2-13", "2022-3-14", "2022-4-16"]
type(dates)
pd.DatetimeIndex(dates)

DatetimeIndex(['2022-02-13', '2022-03-14', '2022-04-16'], dtype='datetime64[ns]', freq=None)

In [36]:
dates =  [dt.date(2022, 2, 13), dt.date(2022,3,4), dt.date(2022,5,16)]
type(dates)

dateindex= pd.DatetimeIndex(dates)
dateindex

DatetimeIndex(['2022-02-13', '2022-03-04', '2022-05-16'], dtype='datetime64[ns]', freq=None)

In [37]:
values = [10,13,20]
pd.Series(data=values, index=dateindex)

2022-02-13    10
2022-03-04    13
2022-05-16    20
dtype: int64

pd.to_datetime

In [38]:
pd.to_datetime('2022-12-03')

Timestamp('2022-12-03 00:00:00')

In [39]:
pd.to_datetime(dt.date(2022,12,3))

Timestamp('2022-12-03 00:00:00')

In [40]:
pd.to_datetime(dt.datetime(2022,12,3,14,34,20))

Timestamp('2022-12-03 14:34:20')

In [41]:
dates=['2022/12/13', '2022/1/23', '2022/4/16']
pd.to_datetime(dates)

DatetimeIndex(['2022-12-13', '2022-01-23', '2022-04-16'], dtype='datetime64[ns]', freq=None)

In [44]:
dates = pd.Series(['December 22nd, 2019', "2019, 12, 22", "This is Date", 'Dec 23rd, 2019', '24th Dec, 2019'])
dates

0    December 22nd, 2019
1           2019, 12, 22
2           This is Date
3         Dec 23rd, 2019
4         24th Dec, 2019
dtype: object

In [45]:
dates = pd.to_datetime(dates, errors='coerce')
dates

0   2019-12-22
1          NaT
2          NaT
3          NaT
4          NaT
dtype: datetime64[ns]

In [51]:
unixtime= [float('12345689'),float('45678901'),float('8904567234')]
pd.to_datetime(unixtime, unit='s')

DatetimeIndex(['1970-05-23 21:21:29', '1971-06-13 16:35:01',
               '2252-03-05 02:53:54'],
              dtype='datetime64[ns]', freq=None)

In [52]:
pd.date_range(start='2016-01-01', end='2016-01-10', freq='D')

DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
               '2016-01-09', '2016-01-10'],
              dtype='datetime64[ns]', freq='D')

In [54]:
from pandas_datareader import data

In [57]:
company = "MSFT"
start = "2019-01-01"
end = "2019-12-22"

Time Delta

In [3]:
timeA = pd.Timestamp('2019-12-2 16:13:12')
timeB = pd.Timestamp('2019-6-6  15:12:1')
timeA - timeB

Timedelta('179 days 01:01:11')

In [10]:
pd.Timedelta( weeks = 10, days = 20 , minutes=20)

Timedelta('90 days 00:20:00')